apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duplicati
spec:
  destination:
    namespace: duplicati
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 5.2.0
    chart: duplicati
    helm:
      values: >-
        codeserver:
          enabled: true
            volumeMounts:
            - mountPath: /config
              name: duplicati-config
            - mountPath: /
              name: traefik
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true