apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
spec:
  destination:
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.gitlab.io/'
    targetRevision: 5.10.0
    chart: gitlab
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true