apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
spec:
  destination:
    namespace: placetime
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops
    repoURL: 'https://git.placetime.team/devops/helm-charts.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
