apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jenkins.io'
    targetRevision: 3.11.10
    chart: jenkins
    helm:
      parameters:
        - name: agent.image
          value: 'docker'
        - name: agent.tag
          value: 'dind'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true