apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10
spec:
  destination:
    namespace: kasten-io
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.kasten.io/'
    targetRevision: 4.5.13
    chart: k10
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true