apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  destination:
    namespace: database
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.0.0
    chart: mysql
    helm:
      parameters:
        - name: image.tag
          value: '8.0-oracle'
        - name: image.repository
          value: arm64v8/mysql
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true