apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
spec:
  destination:
    namespace: database
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.9.0
    chart: mysql
    helm:
      parameters:
        - name: auth.database
          value: telegram
        - name: auth.username
          value: dbadmin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true