apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.2.0
    helm:
      values: |
        config:
          lokiAddress: http://loki-gateway/loki/api/v1/push
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true