apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 15.5.4
    chart: prometheus
    helm:
      parameters:
        - name: pushgateway.persistentVolume.size
          value: 3Gi
        - name: server.persistentVolume.size
          value: 3Gi
        - name: alertmanager.persistentVolume.size
          value: 3Gi
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true