apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  destination:
    namespace: rancher
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://releases.rancher.com/server-charts/latest'
    targetRevision: 2.6.5-rc2
    chart: rancher
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true