apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  destination:
    namespace: rancher
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://releases.rancher.com/server-charts/stable'
    targetRevision: 2.6.4
    chart: rancher
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crd
spec:
  destination:
    namespace: rancher
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: rancher
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.8.0
    chart: cert-manager
    helm:
      values: |-
        hostname=rancher-cluster.kuberstar.com \
        bootstrapPassword=admin \
        ingress.tls.source=letsEncrypt \
        letsEncrypt.email=djzero81@gmail.com \
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true