apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  destination:
    namespace: cattle-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://releases.rancher.com/server-charts/stable'
    targetRevision: 2.6.4
    chart: rancher
    helm:
      parameters:
        - name: hostname
          value: rancher.172.16.0.153.nip.io
        - name: bootstrapPassword
          value: admin
        - name: ingress.tls.source
          value: letsEncrypt
        - name: letsEncrypt.email
          value: djzero81@gmail.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cattle-system
    server: 'https://kubernetes.default.svc'
  source:
    path: cert-manager
    repoURL: 'https://github.com/m-minasyan/helm.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: cert-manager
#spec:
#  destination:
#    namespace: cattle-system
#    server: 'https://kubernetes.default.svc'
#  source:
#    path: cert-manager
#    repoURL: 'https://github.com/m-minasyan/helm.git'
#    targetRevision: main
#  project: default
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true