apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 10.15.0
    chart: traefik
    helm:
      values: >-
        globalArguments:
          - "--global.checknewversion"
        additionalArguments:
          - "--certificatesresolvers.le.acme.storage=/data/acme.json"
          - "--certificatesresolvers.myresolver.acme.email=minasyan.business@gmail.com"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=websecure"
        env:
         - name: CF_API_EMAIL
           value: minasyan.business@gmail.com
         - name: CF_API_KEY
           valueFrom:
             secretKeyRef:
               name: traefik-cloudflare-secret
               key: CF_API_KEY
        persistence:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true